version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings.
    columns:
      - name: listing_id
        tests:
          - unique
          - not_null

      - name: host_id
        description: Cleansed table which contains Airbnb hosts.
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: Type of Rooms.
        tests:
          - accepted_values:
              values: ['Entire home/apt',
                       'Private room',
                       'Shared room', 
                       'Hotel room']

      - name: minimum_nights
        tests:
          - positive_value