version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings.
    columns:
      - name: listing_id
        tests:
          - unique
          - not_null

      - name: host_id
        description: The id of the host.
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: Type of Rooms.
        tests:
          - accepted_values:
              values: ['Entire home/apt',
                       'Private room',
                       'Shared room', 
                       'Hotel room']

      - name: minimum_nights
        tests:
          - positive_value
  
  - name: 'dim_hosts_cleansed'
    description: Cleansed table which contains Airbnb hosts.
    columns:
      - name: host_id
        description: The id of the host.
        tests:
          - not_null
          - unique

      - name: host_name
        description: The name of the host.
        tests:
          - not_null
      
      - name: is_superhost
        description: Defines whether the hosts is a superhost
        tests:
          - accepted_values:
              values: ['TRUE','FALSE']