version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        identifiers: raw_listings
      - name: hosts
        identifiers: raw_hosts
      - name: raw_reviews
        identifiers: raw_reviews
        loaded_at_field: date
        freshness:
          warn_after: {count: 4, period: hour}
          error_after: {count: 24, period: hour}